package views;

import javax.swing.JOptionPane;
import data.Persistencia;
import domain.*;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author LautaroCastillo
 */
public class AgregarAnimalView extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAnimalView
     */
    public AgregarAnimalView() {
        initComponents();
        setTitle("Agregar Animal");
        //setBounds(500, 200, 800, 600);
        setLocationRelativeTo(null);
        setSize(450, 520); // Ancho: 800 px, Alto: 600 px
        
        jTextFieldPorcentajeFijo.setEnabled(false);
        jTextFieldKgFijos.setEnabled(false);
        
        paises = Controlador.getPaises();
        sectoresDisponibles = Controlador.getSectores();
        jComboBoxSector.removeAllItems();
        jComboBoxSector.addItem("Seleccione:");
        actualizarComboPaises();
        
    }
    
    private ArrayList<Sector> sectoresDisponibles;
    private ArrayList<Pais> paises;

    
    private void actualizarComboSectores(String tipoAlimentacion) {
        jComboBoxSector.removeAllItems();
        jComboBoxSector.addItem("Seleccione:");
        for (Sector sector : sectoresDisponibles) {
            if (sector.getTipoAlimentacion().toString().equalsIgnoreCase(tipoAlimentacion)) {
                jComboBoxSector.addItem(sector.toString());
            }
        }
    }
    
    private void actualizarComboPaises(){
    jComboBoxPais.removeAllItems();
    jComboBoxPais.addItem("Seleccione:");

    for (Pais pais : paises){
        jComboBoxPais.addItem(pais.toString());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEspecie = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jComboBoxAlimentacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelPorcentaje = new javax.swing.JLabel();
        jTextFieldPorcentajeFijo = new javax.swing.JTextField();
        jLabelKilogramos = new javax.swing.JLabel();
        jTextFieldKgFijos = new javax.swing.JTextField();
        jLabelSector = new javax.swing.JLabel();
        jComboBoxSector = new javax.swing.JComboBox<>();
        jButtonAgregarAnimal = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEspecie = new javax.swing.JTextField();
        jComboBoxPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabelEspecie.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelEspecie.setText("Especie:");

        jLabelEdad.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelEdad.setText("Edad:");

        jTextFieldEdad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabelPeso.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelPeso.setText("Peso:");

        jTextFieldPeso.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jComboBoxAlimentacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jComboBoxAlimentacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "CARNIVORO", "HERBIVORO" }));
        jComboBoxAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlimentacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setText("Alimentación:");

        jLabelPorcentaje.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelPorcentaje.setText("% Fijo:");

        jTextFieldPorcentajeFijo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldPorcentajeFijo.setToolTipText("Ingresa el Porcentaje Fijo de Comida para el Carnívoro (ej: 0.20; 0.05; 0.50).");

        jLabelKilogramos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelKilogramos.setText("kg Fijos:");

        jTextFieldKgFijos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextFieldKgFijos.setToolTipText("Ingresa los kilogramos fijos de comida para el Herbívoro (ej: 170; 250.5)");

        jLabelSector.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelSector.setText("Sector:");

        jComboBoxSector.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jComboBoxSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:" }));
        jComboBoxSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSectorActionPerformed(evt);
            }
        });

        jButtonAgregarAnimal.setBackground(new java.awt.Color(51, 102, 0));
        jButtonAgregarAnimal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonAgregarAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarAnimal.setText("Agregar");
        jButtonAgregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAnimalActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(153, 51, 0));
        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("País:");

        jComboBoxPais.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonAgregarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPorcentajeFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSector, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKgFijos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPorcentajeFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldKgFijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlimentacionActionPerformed
        String seleccion = (String) jComboBoxAlimentacion.getSelectedItem();

        if (seleccion.equals("CARNIVORO")) {
            jTextFieldPorcentajeFijo.setEnabled(true);
            jTextFieldKgFijos.setEnabled(false);
            jTextFieldKgFijos.setText("");
        } else if (seleccion.equals("HERBIVORO")) {
            jTextFieldKgFijos.setEnabled(true);
            jTextFieldPorcentajeFijo.setEnabled(false);
            jTextFieldPorcentajeFijo.setText("");
        } else {
            jTextFieldKgFijos.setEnabled(false);
            jTextFieldPorcentajeFijo.setEnabled(false);
            jTextFieldKgFijos.setText("");
            jTextFieldPorcentajeFijo.setText("");
        }

        if (!seleccion.equals("Seleccione:")) {
            actualizarComboSectores(seleccion);
        }
    }//GEN-LAST:event_jComboBoxAlimentacionActionPerformed

    private void jButtonAgregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAnimalActionPerformed
    String especieNombre = jTextFieldEspecie.getText().trim();
    String edadString = jTextFieldEdad.getText().trim();
    String pesoString = jTextFieldPeso.getText().trim();
    String tipo = (String) jComboBoxAlimentacion.getSelectedItem();
    String porcentajeFijo = jTextFieldPorcentajeFijo.getText().trim();
    String kgFijos = jTextFieldKgFijos.getText().trim();
    String sectorString = (String) jComboBoxSector.getSelectedItem();
    String paisSeleccionado = (String) jComboBoxPais.getSelectedItem();

    // Validación de campos obligatorios
    if (especieNombre.isEmpty() || edadString.isEmpty() || pesoString.isEmpty()
        || tipo.equals("Seleccione:") || sectorString.equals("Seleccione:")
        || paisSeleccionado == null || paisSeleccionado.toString().equals("Seleccione:")) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos obligatorios.");
        return;
    }

    // Validación según el tipo
    if (tipo.equals("CARNIVORO") && porcentajeFijo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el porcentaje fijo para el carnívoro.");
        return;
    }

    if (tipo.equals("HERBIVORO") && kgFijos.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese los kilogramos fijos para el herbívoro.");
        return;
    }

    try {
        int edad = Integer.parseInt(edadString);
        double peso = Double.parseDouble(pesoString);
        Mamifero nuevo = null;

        // Buscar o crear especie
        Especie especie = Controlador.getEspeciePorNombre(especieNombre);
        if (especie == null) {
            especie = new Especie(especieNombre, TipoAlimentacion.valueOf(tipo),
                tipo.equals("CARNIVORO") ? Double.parseDouble(porcentajeFijo) : 0);
            Controlador.getEspecies().add(especie);
        }

        // Buscar sector
        Sector sector = Controlador.getSectorPorDescripcion(sectorString);
        if (sector == null) {
            JOptionPane.showMessageDialog(null, "Sector no encontrado.");
            return;
        }

        // Crear animal según tipo y pasar el país
        if (tipo.equals("CARNIVORO")) {
            nuevo = new Carnivoro(edad, peso, especie, sector, paisSeleccionado);
        } else {
            double kg = Double.parseDouble(kgFijos);
            nuevo = new Herbivoro(edad, peso, especie, sector, paisSeleccionado, kg);
        }

        Controlador.agregarAnimal(nuevo);
        JOptionPane.showMessageDialog(null, "Animal agregado correctamente.");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al agregar animal: " + e.getMessage());
    }
    
     // Limpiar los campos de texto y reiniciar los ComboBox
        jTextFieldEspecie.setText("");
        jTextFieldEdad.setText("");
        jTextFieldPeso.setText("");
        jTextFieldPorcentajeFijo.setText("");
        jTextFieldKgFijos.setText(""); 
        jComboBoxAlimentacion.setSelectedIndex(0);
        jComboBoxSector.setSelectedIndex(0);
        jComboBoxPais.setSelectedIndex(0);    
        
    }//GEN-LAST:event_jButtonAgregarAnimalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.dispose();
        MenuPrincipalView menu = new MenuPrincipalView();
        menu.setVisible(true);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSectorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBoxSectorActionPerformed

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAnimalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAnimalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarAnimal;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxAlimentacion;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JComboBox<String> jComboBoxSector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEspecie;
    private javax.swing.JLabel jLabelKilogramos;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPorcentaje;
    private javax.swing.JLabel jLabelSector;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldEspecie;
    private javax.swing.JTextField jTextFieldKgFijos;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPorcentajeFijo;
    // End of variables declaration//GEN-END:variables





}
